[package]
name = "tranzistorak"
version = "3.2.0"
edition = "2021"

[dependencies]
invidious = { version = "0.7.0", features = ["reqwest_async"]}
rand = "0.8.5"
rspotify = "0.11.7"

[dependencies.tokio]
version = "1.21.2"
features = ["macros", "rt-multi-thread"]

[dependencies.serenity]
version = "0.11"
default-features = false
features = ["builder", "cache", "client", "gateway", "http", "model", "utils", "voice", "rustls_backend"]

[dependencies.songbird]
version = "0.3.2"
features = ["yt-dlp"]
