[package]
name = "tranzistorak"
version = "3.2.5"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
invidious = { version = "0.7.6", features = ["reqwest_async"]}
rand = "0.9.0"
rspotify = "0.14.0"
reqwest = "0.12.12"
tracing-subscriber = "0.3.19"

[dependencies.tokio]
version = "1.44.0"
features = ["macros", "rt-multi-thread"]

[dependencies.serenity]
version = "0.12.4"
default-features = false
features = ["builder", "cache", "client", "gateway", "http", "model", "utils", "voice", "rustls_backend"]

[dependencies.songbird]
version = "0.5.0"

[dependencies.symphonia]
version = "0.5.4"
features = ["all"]
