[package]
name = "tranzistorak"
version = "3.2.2"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
invidious = { version = "0.7.0", features = ["reqwest_async"]}
rand = "0.8.5"
rspotify = "0.13.1"
rustls = "0.21.11"
mio = "0.8.11"
tungstenite = "0.20.1"
h2 = "0.3.26"
openssl = "0.10.60"
rustix = "0.38.19"

[dependencies.tokio]
version = "1.21.2"
features = ["macros", "rt-multi-thread"]

[dependencies.serenity]
version = "0.11"
default-features = false
features = ["builder", "cache", "client", "gateway", "http", "model", "utils", "voice", "rustls_backend"]

[dependencies.songbird]
version = "0.3.2"
features = ["yt-dlp"]
