[package]
name = "tranzistorak"
version = "3.2.3"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
invidious = { version = "0.7.0", features = ["reqwest_async"]}
rand = "0.8.5"
rspotify = "0.13.1"
rustls = "0.23.12"
mio = "1.0.1"
tungstenite = "0.23.0"
h2 = "0.4.5"
openssl = "0.10.60"
rustix = "0.38.19"
reqwest = "0.11.27"
tracing-subscriber = "0.3.18"
symphonia = "0.5.2"

[dependencies.tokio]
version = "1.21.2"
features = ["macros", "rt-multi-thread"]

[dependencies.serenity]
version = "0.12.2"
default-features = false
features = ["builder", "cache", "client", "gateway", "http", "model", "utils", "voice", "rustls_backend"]

[dependencies.songbird]
version = "0.4.3"
