services:
  tranzistorak:
    container_name: tranzistorak
    build: .
    volumes:
      - ./logs:/srv/bot/logs
      - ./rusty_pipe_storage:/srv/bot/rusty_pipe_storage
      - ./transcription_model:/srv/bot/transcription_model
    networks:
      - default
    restart: always

networks:
  default:
    driver: bridge
