---
name: Docker build check
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, reopened, synchronize]
permissions: {}
jobs:
  check:
    name: Docker build check
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Code checkout
        uses: https://github.com/actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: .env symlink creation
        run: ln -s .env.example .env

      - name: Check
        uses: https://codeberg.org/matous-volf/action-docker-build-check@22807d6890d14a1dd47a5e2535b1be9eb7d8c3e6 # v3.0.0
        with:
          compose_file: docker-compose.yaml
