---
name: Rust check
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, reopened, synchronize]
permissions: {}
jobs:
  check:
    name: Rust check
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Dependencies installation
        run: |
          DEPENDENCIES=(
            # renovate: repology=ubuntu_24_04/cmake
            cmake=3.28.3-1build7
            # renovate: repology=ubuntu_24_04/alsa-lib
            libasound2-dev=1.2.11-1ubuntu0.3
            # renovate: repology=ubuntu_24_04/libonig-dev
            libonig-dev=6.9.9-1build1
          )
          apt-get update && apt-get install -y "${DEPENDENCIES[@]}"

      - name: Code checkout
        uses: https://github.com/actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: .env symlink creation
        run: ln -s .env.example .env

      - name: Check
        uses: https://codeberg.org/matous-volf/action-rust-check@8269a908a15f836b84679c73dfd349ddebfe9bb1 # v7.0.0
        with:
          rust_version: 1.97.1
          run_tests: false
          lint_docs: false
