---
name: Rust check
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, reopened, synchronize]
permissions: {}
jobs:
  check:
    name: Rust check
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Code checkout
        uses: https://github.com/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Check
        uses: https://codeberg.org/matous-volf/action-rust-check@89a31dc65ef1d8d666da28b061da4d536c58494a # v14.0.0
        with:
          system_dependencies: |
            # renovate: repology=alpine_3_24/alsa-lib-dev
            alsa-lib-dev=1.2.15.3-r0
            # renovate: repology=alpine_3_24/cmake
            cmake=4.2.3-r0
            # renovate: repology=alpine_3_24/build-base
            build-base=0.5-r4
            # renovate: repology=alpine_3_24/g++
            g++=15.2.0-r5
            # renovate: repology=alpine_3_24/oniguruma-dev
            oniguruma-dev=6.9.10-r0
            # renovate: repology=alpine_3_24/openssl-dev
            openssl-dev=3.5.7-r0
          pre_command: |
            ln -s .env.example .env
            export RUSTFLAGS="-C target-feature=-crt-static"
            export CXXFLAGS="-D_LARGEFILE64_SOURCE -Dstat64=stat -Dfstat64=fstat"
          check_advisories: false
          lint_docs: false
          run_tests: false
          check_semver: false
          check_msrv: false
