---
name: Rust check
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, reopened, synchronize]
permissions: {}
jobs:
  check:
    name: Rust check
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Dependencies installation
        run: |
          DEPENDENCIES=(
            # renovate: repology=ubuntu_24_04/cmake
            cmake=3.28.3-1build7
            # renovate: repology=ubuntu_24_04/alsa-lib
            libasound2-dev=1.2.11-1ubuntu0.2
            # renovate: repology=ubuntu_24_04/oniguruma
            libonig-dev=6.9.9-1build1
          )
          apt-get update && apt-get install -y "${DEPENDENCIES[@]}"

      - name: Code checkout
        uses: https://github.com/actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      - name: .env symlink creation
        run: ln -s .env.example .env

      - name: Check
        uses: https://codeberg.org/matous-volf/action-rust-check@f0c0a5b4c3079b21f07a684d9c9b7ef642097f1a # v1.0.0
        with:
          rust_version: 1.96.0
          run_tests: false
