---
name: ShellCheck check
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, reopened, synchronize]
permissions: {}
jobs:
  check:
    name: ShellCheck check
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Code checkout
        uses: https://github.com/actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Check
        uses: https://codeberg.org/matous-volf/action-shellcheck-check@7ebe7977e7f044d331c71801013a72addb9d7655 # v1.0.0
