---
name: ShellCheck check
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, reopened, synchronize]
permissions: {}
jobs:
  check:
    name: ShellCheck check
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Code checkout
        uses: https://github.com/actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      - name: Check
        uses: https://codeberg.org/matous-volf/action-shellcheck-check@7ebe7977e7f044d331c71801013a72addb9d7655 # v1.0.0
