---
name: Rust check

on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions: {}

jobs:
  build:
    name: Rust check
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: read
      packages: read
      statuses: write
    steps:
      - name: Rust toolchain installation
        uses: dtolnay/rust-toolchain@0d72692bcfbf448b1e2afa01a67f71b455a9dcec # 1.86.0
        with:
          components: clippy, rustfmt
      - name: code checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
      - name: .env symlink creation
        run: ln -s .env.example .env
      - name: rustfmt check
        run: cargo fmt --all --check
      - name: Clippy check
        run: cargo clippy --all-targets --all-features -- --deny warnings
      - name: test check
        run: cargo test --all --all-targets --all-features
