---
name: yamllint check

on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions: {}

jobs:
  build:
    name: yamllint check
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: read
      packages: read
      statuses: write
    steps:
      - name: yamllint installation
        run: sudo apt-get update && sudo apt-get install -y yamllint=1.26.3-1
      - name: code checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
      - name: yamllint check
        run: yamllint -c .github/config/yamllint.yaml .
